const  mockData = [
    {
      "creative_id": "120214081337200001",
      "creative_name": "Dummy Creative 1",
      "tags": [
        "Concept:Character Introduction",
        "Audio - Type:music",
        "Audio - Language:French",
        "End card elements - CTA:Get Started!",
        "End card elements - Objects:magic wand",
        "End card elements - Language:French",
        "End card elements - CTA Placement:Bottom-Center",
        "End card elements - Background Colour:Yellow",
        "End card elements - Background setting:outer space",
        "End card elements - CTA background colour:Black"
      ],
      "country": "ES",
      "ad_network": "google",
      "os": "unknown",
      "campaign": "Dummy Campaign A",
      "ad_group": "Group A",
      "ipm": 2.59,
      "ctr": 0.811309,
      "spend": 11.79,
      "impressions": 7942,
      "clicks": 68,
      "cpm": 0.680457,
      "cost_per_click": 0.140801,
      "cost_per_install": 0.350868128,
      "installs": 27
    },
    {
      "creative_id": "120214081337200002",
      "creative_name": "Dummy Creative 2",
      "tags": [
        "Concept:Product Feature",
        "Audio - Type:music",
        "Audio - Language:French",
        "End card elements - CTA:Join now!",
        "End card elements - Objects:magic wand",
        "End card elements - Language:Spanish",
        "End card elements - CTA Placement:Bottom-Center",
        "End card elements - Background Colour:Yellow",
        "End card elements - Background setting:volcano",
        "End card elements - CTA background colour:Gold"
      ],
      "country": "AU",
      "ad_network": "google",
      "os": "Android",
      "campaign": "Dummy Campaign B",
      "ad_group": "Group B",
      "ipm": 2.92,
      "ctr": 0.76847,
      "spend": 6.21,
      "impressions": 11810,
      "clicks": 76,
      "cpm": 0.838777,
      "cost_per_click": 0.054077,
      "cost_per_install": 0.3292279504,
      "installs": 16
    },
    {
      "creative_id": "120214081337200003",
      "creative_name": "Dummy Creative 3",
      "tags": [
        "Concept:Gameplay",
        "Audio - Type:background music",
        "Audio - Language:English",
        "End card elements - CTA:Explore now!",
        "End card elements - Objects:spaceship",
        "End card elements - Language:Spanish",
        "End card elements - CTA Placement:Top-Right",
        "End card elements - Background Colour:Grey",
        "End card elements - Background setting:medieval",
        "End card elements - CTA background colour:Black"
      ],
      "country": "DE",
      "ad_network": "google",
      "os": "iOS",
      "campaign": "Dummy Campaign C",
      "ad_group": "Group C",
      "ipm": 2.67,
      "ctr": 0.849848,
      "spend": 3.97,
      "impressions": 5720,
      "clicks": 42,
      "cpm": 0.675052,
      "cost_per_click": 0.137178,
      "cost_per_install": 0.215922832,
      "installs": 11
    },
    {
      "creative_id": "120214081337200004",
      "creative_name": "Dummy Creative 4",
      "tags": [
        "Concept:UGC",
        "Audio - Type:voiceover",
        "Audio - Language:Spanish",
        "End card elements - CTA:Join now!",
        "End card elements - Objects:dragon",
        "End card elements - Language:English",
        "End card elements - CTA Placement:Top-Right",
        "End card elements - Background Colour:Green",
        "End card elements - Background setting:castle",
        "End card elements - CTA background colour:Black"
      ],
      "country": "UK",
      "ad_network": "meta",
      "os": "iOS",
      "campaign": "Dummy Campaign D",
      "ad_group": "Group D",
      "ipm": 2.57,
      "ctr": 0.703278,
      "spend": 2.33,
      "impressions": 7712,
      "clicks": 83,
      "cpm": 0.813637,
      "cost_per_click": 0.109865,
      "cost_per_install": 0.2999721245,
      "installs": 38
    },
    {
      "creative_id": "120214081337200005",
      "creative_name": "Dummy Creative 5",
      "tags": [
        "Concept:Product Feature",
        "Audio - Type:voiceover",
        "Audio - Language:English",
        "End card elements - CTA:Explore now!",
        "End card elements - Objects:shield",
        "End card elements - Language:German",
        "End card elements - CTA Placement:Top-Left",
        "End card elements - Background Colour:Blue",
        "End card elements - Background setting:forest",
        "End card elements - CTA background colour:Gold"
      ],
      "country": "FR",
      "ad_network": "meta",
      "os": "Android",
      "campaign": "Dummy Campaign E",
      "ad_group": "Group E",
      "ipm": 1.76,
      "ctr": 0.826058,
      "spend": 11.02,
      "impressions": 11984,
      "clicks": 73,
      "cpm": 0.699254,
      "cost_per_click": 0.138809,
      "cost_per_install": 0.3240039005,
      "installs": 35
    },
    {
      "creative_id": "120214081337200006",
      "creative_name": "Dummy Creative 6",
      "tags": [
        "Concept:Character Introduction",
        "Audio - Type:voiceover",
        "Audio - Language:Spanish",
        "End card elements - CTA:Get Started!",
        "End card elements - Objects:shield",
        "End card elements - Language:French",
        "End card elements - CTA Placement:Top-Center",
        "End card elements - Background Colour:Green",
        "End card elements - Background setting:castle",
        "End card elements - CTA background colour:Black"
      ],
      "country": "FR",
      "ad_network": "google",
      "os": "iOS",
      "campaign": "Dummy Campaign F",
      "ad_group": "Group F",
      "ipm": 2.62,
      "ctr": 0.877871,
      "spend": 5.88,
      "impressions": 13690,
      "clicks": 97,
      "cpm": 0.787468,
      "cost_per_click": 0.104874,
      "cost_per_install": 0.2944444482,
      "installs": 30
    },
    {
      "creative_id": "120214081337200007",
      "creative_name": "Dummy Creative 7",
      "tags": [
        "Concept:UGC",
        "Audio - Type:background music",
        "Audio - Language:German",
        "End card elements - CTA:Explore now!",
        "End card elements - Objects:magic wand",
        "End card elements - Language:German",
        "End card elements - CTA Placement:Top-Left",
        "End card elements - Background Colour:Grey",
        "End card elements - Background setting:outer space",
        "End card elements - CTA background colour:Black"
      ],
      "country": "IN",
      "ad_network": "google",
      "os": "unknown",
      "campaign": "Dummy Campaign G",
      "ad_group": "Group G",
      "ipm": 1.66,
      "ctr": 0.605504,
      "spend": 2.08,
      "impressions": 9695,
      "clicks": 96,
      "cpm": 0.719608,
      "cost_per_click": 0.1058,
      "cost_per_install": 0.2394450623,
      "installs": 13
    },
    {
      "creative_id": "120214081337200008",
      "creative_name": "Dummy Creative 8",
      "tags": [
        "Concept:Gameplay",
        "Audio - Type:music",
        "Audio - Language:French",
        "End card elements - CTA:Play now!",
        "End card elements - Objects:dragon",
        "End card elements - Language:German",
        "End card elements - CTA Placement:Top-Left",
        "End card elements - Background Colour:Grey",
        "End card elements - Background setting:castle",
        "End card elements - CTA background colour:Gold"
      ],
      "country": "DE",
      "ad_network": "google",
      "os": "iOS",
      "campaign": "Dummy Campaign H",
      "ad_group": "Group H",
      "ipm": 1.65,
      "ctr": 0.874549,
      "spend": 11.25,
      "impressions": 12247,
      "clicks": 93,
      "cpm": 0.792566,
      "cost_per_click": 0.112568,
      "cost_per_install": 0.2381623106,
      "installs": 13
    },
    {
      "creative_id": "120214081337200009",
      "creative_name": "Dummy Creative 9",
      "tags": [
        "Concept:UGC",
        "Audio - Type:music",
        "Audio - Language:German",
        "End card elements - CTA:Play now!",
        "End card elements - Objects:shield",
        "End card elements - Language:German",
        "End card elements - CTA Placement:Bottom-Left",
        "End card elements - Background Colour:Red",
        "End card elements - Background setting:outer space",
        "End card elements - CTA background colour:Blue"
      ],
      "country": "US",
      "ad_network": "meta",
      "os": "iOS",
      "campaign": "Dummy Campaign I",
      "ad_group": "Group I",
      "ipm": 2.93,
      "ctr": 0.731448,
      "spend": 8.6,
      "impressions": 12093,
      "clicks": 112,
      "cpm": 0.586385,
      "cost_per_click": 0.082362,
      "cost_per_install": 0.2418347382,
      "installs": 29
    },
    {
      "creative_id": "120214081337200010",
      "creative_name": "Dummy Creative 10",
      "tags": [
        "Concept:Character Introduction",
        "Audio - Type:background music",
        "Audio - Language:Spanish",
        "End card elements - CTA:Download Now!",
        "End card elements - Objects:shield",
        "End card elements - Language:Spanish",
        "End card elements - CTA Placement:Bottom-Left",
        "End card elements - Background Colour:Blue",
        "End card elements - Background setting:volcano",
        "End card elements - CTA background colour:Purple"
      ],
      "country": "DE",
      "ad_network": "google",
      "os": "unknown",
      "campaign": "Dummy Campaign J",
      "ad_group": "Group J",
      "ipm": 2.54,
      "ctr": 0.632565,
      "spend": 7.63,
      "impressions": 6201,
      "clicks": 53,
      "cpm": 0.880301,
      "cost_per_click": 0.135799,
      "cost_per_install": 0.2733362534,
      "installs": 18
    },
    {
      "creative_id": "120214081337200011",
      "creative_name": "Dummy Creative 11",
      "tags": [
        "Concept:Product Feature",
        "Audio - Type:voiceover",
        "Audio - Language:French",
        "End card elements - CTA:Join now!",
        "End card elements - Objects:spaceship",
        "End card elements - Language:French",
        "End card elements - CTA Placement:Top-Center",
        "End card elements - Background Colour:Red",
        "End card elements - Background setting:castle",
        "End card elements - CTA background colour:Blue"
      ],
      "country": "AU",
      "ad_network": "meta",
      "os": "iOS",
      "campaign": "Dummy Campaign K",
      "ad_group": "Group K",
      "ipm": 1.92,
      "ctr": 0.887769,
      "spend": 2.51,
      "impressions": 9398,
      "clicks": 72,
      "cpm": 0.848972,
      "cost_per_click": 0.134473,
      "cost_per_install": 0.2284062675,
      "installs": 25
    },
    {
      "creative_id": "120214081337200012",
      "creative_name": "Dummy Creative 12",
      "tags": [
        "Concept:Gameplay",
        "Audio - Type:music",
        "Audio - Language:Spanish",
        "End card elements - CTA:Get Started!",
        "End card elements - Objects:shield",
        "End card elements - Language:French",
        "End card elements - CTA Placement:Bottom-Left",
        "End card elements - Background Colour:Blue",
        "End card elements - Background setting:volcano",
        "End card elements - CTA background colour:Purple"
      ],
      "country": "FR",
      "ad_network": "meta",
      "os": "Android",
      "campaign": "Dummy Campaign L",
      "ad_group": "Group L",
      "ipm": 2.51,
      "ctr": 0.861936,
      "spend": 3.4,
      "impressions": 13130,
      "clicks": 68,
      "cpm": 0.566231,
      "cost_per_click": 0.055731,
      "cost_per_install": 0.2192987886,
      "installs": 35
    },
    {
      "creative_id": "120214081337200013",
      "creative_name": "Dummy Creative 13",
      "tags": [
        "Concept:Product Feature",
        "Audio - Type:background music",
        "Audio - Language:Spanish",
        "End card elements - CTA:Explore now!",
        "End card elements - Objects:dragon",
        "End card elements - Language:German",
        "End card elements - CTA Placement:Bottom-Center",
        "End card elements - Background Colour:Yellow",
        "End card elements - Background setting:castle",
        "End card elements - CTA background colour:Dark Green"
      ],
      "country": "DE",
      "ad_network": "google",
      "os": "unknown",
      "campaign": "Dummy Campaign M",
      "ad_group": "Group M",
      "ipm": 2.37,
      "ctr": 0.630917,
      "spend": 3.42,
      "impressions": 8623,
      "clicks": 109,
      "cpm": 0.732898,
      "cost_per_click": 0.061207,
      "cost_per_install": 0.2867020802,
      "installs": 23
    },
    {
      "creative_id": "120214081337200014",
      "creative_name": "Dummy Creative 14",
      "tags": [
        "Concept:Gameplay",
        "Audio - Type:background music",
        "Audio - Language:French",
        "End card elements - CTA:Join now!",
        "End card elements - Objects:spaceship",
        "End card elements - Language:English",
        "End card elements - CTA Placement:Top-Center",
        "End card elements - Background Colour:Grey",
        "End card elements - Background setting:volcano",
        "End card elements - CTA background colour:Purple"
      ],
      "country": "CA",
      "ad_network": "meta",
      "os": "unknown",
      "campaign": "Dummy Campaign N",
      "ad_group": "Group N",
      "ipm": 1.88,
      "ctr": 0.885317,
      "spend": 10.24,
      "impressions": 6270,
      "clicks": 89,
      "cpm": 0.827277,
      "cost_per_click": 0.137619,
      "cost_per_install": 0.3247441936,
      "installs": 15
    },
    {
      "creative_id": "120214081337200015",
      "creative_name": "Dummy Creative 15",
      "tags": [
        "Concept:Product Feature",
        "Audio - Type:voiceover",
        "Audio - Language:French",
        "End card elements - CTA:Play now!",
        "End card elements - Objects:magic wand",
        "End card elements - Language:Spanish",
        "End card elements - CTA Placement:Top-Center",
        "End card elements - Background Colour:Green",
        "End card elements - Background setting:volcano",
        "End card elements - CTA background colour:Gold"
      ],
      "country": "FR",
      "ad_network": "google",
      "os": "unknown",
      "campaign": "Dummy Campaign O",
      "ad_group": "Group O",
      "ipm": 2.74,
      "ctr": 0.806284,
      "spend": 6.0,
      "impressions": 12350,
      "clicks": 58,
      "cpm": 0.606032,
      "cost_per_click": 0.138042,
      "cost_per_install": 0.2028075254,
      "installs": 48
    },
    {
      "creative_id": "120214081337200016",
      "creative_name": "Dummy Creative 16",
      "tags": [
        "Concept:Character Introduction",
        "Audio - Type:voiceover",
        "Audio - Language:German",
        "End card elements - CTA:Explore now!",
        "End card elements - Objects:spaceship",
        "End card elements - Language:English",
        "End card elements - CTA Placement:Top-Right",
        "End card elements - Background Colour:Yellow",
        "End card elements - Background setting:forest",
        "End card elements - CTA background colour:Gold"
      ],
      "country": "FR",
      "ad_network": "google",
      "os": "unknown",
      "campaign": "Dummy Campaign P",
      "ad_group": "Group P",
      "ipm": 2.38,
      "ctr": 0.74493,
      "spend": 9.46,
      "impressions": 13708,
      "clicks": 90,
      "cpm": 0.616502,
      "cost_per_click": 0.149259,
      "cost_per_install": 0.3856324352,
      "installs": 10
    },
    {
      "creative_id": "120214081337200017",
      "creative_name": "Dummy Creative 17",
      "tags": [
        "Concept:Character Introduction",
        "Audio - Type:voiceover",
        "Audio - Language:German",
        "End card elements - CTA:Explore now!",
        "End card elements - Objects:spaceship",
        "End card elements - Language:English",
        "End card elements - CTA Placement:Bottom-Center",
        "End card elements - Background Colour:Green",
        "End card elements - Background setting:volcano",
        "End card elements - CTA background colour:Dark Green"
      ],
      "country": "ES",
      "ad_network": "google",
      "os": "unknown",
      "campaign": "Dummy Campaign Q",
      "ad_group": "Group Q",
      "ipm": 1.9,
      "ctr": 0.725874,
      "spend": 7.09,
      "impressions": 11013,
      "clicks": 90,
      "cpm": 0.896499,
      "cost_per_click": 0.103922,
      "cost_per_install": 0.3763092257,
      "installs": 12
    },
    {
      "creative_id": "120214081337200018",
      "creative_name": "Dummy Creative 18",
      "tags": [
        "Concept:UGC",
        "Audio - Type:music",
        "Audio - Language:French",
        "End card elements - CTA:Explore now!",
        "End card elements - Objects:dragon",
        "End card elements - Language:English",
        "End card elements - CTA Placement:Bottom-Center",
        "End card elements - Background Colour:Yellow",
        "End card elements - Background setting:forest",
        "End card elements - CTA background colour:Gold"
      ],
      "country": "DE",
      "ad_network": "google",
      "os": "iOS",
      "campaign": "Dummy Campaign R",
      "ad_group": "Group R",
      "ipm": 2.79,
      "ctr": 0.793094,
      "spend": 11.27,
      "impressions": 12169,
      "clicks": 84,
      "cpm": 0.798583,
      "cost_per_click": 0.145021,
      "cost_per_install": 0.2388397749,
      "installs": 29
    }
  ]

  export default mockData;